#!/usr/bin/python
import enchant
import sys
import string
def onlyLetters(w): return w.strip(string.punctuation)

lang = sys.argv[1]
words = [ onlyLetters(w) for w in  sys.stdin.read().split() ]
d = enchant.Dict(lang)
unknown = set( [ w + "\n" for w in words if not d.check(w) ] )
sys.stdout.writelines(unknown)
