ReceiptEmailTitle client@Text firstDay@Day lastDay@Day part@Text: Asiakkaan #{client} kirjanpitoaineisto ajalta #{fmtDay firstDay} - #{fmtDay lastDay} #{part}
MoreReceiptsEmailTitle client@Text firstDay@Day lastDay@Day part@Text: Lisäys asiakkaan #{client} kirjanpitoaineistoon ajalta #{fmtDay firstDay} - #{fmtDay lastDay} #{part}
January:Tammikuu
February:Helmikuu
March:Maaliskuu
April:Huhtikuu
May:Toukokuu
June:Kesäkuu
July:Heinäkuu
August:Elokuu
September:Syyskuu
October:Lokakuu
November:Marraskuu
December:Joulukuu
