function __(k,d) {
    var strings = {
        'textmessageform.title' : 'Lähetettävän tekstiviestin muokkaus',
        'text' : 'Teksti',
        'textEditor' : 'Teksti',
        'textmessageform.abort' : 'Keskeytä tekstiviestin lähetys',
        'textmessageform.send' : 'Lähetä tekstiviesti vastaanottajille',
        'textmessageform.replyToText' : 'Vastaus viestiin',
        'receivedtextmessageform.title' : 'Vastaanotettu tekstiviesti',
        'receivedtextmessageform.reply' : 'Vastaa tekstiviestiin',
        'textmessageform.length' : 'Tekstiviestin pituus',
        'textmessageform.lengthMessage' : '{0} merkkiä, {1} viestiä, {2} merkkiä per viesti. Merkkejä jäljellä: {3}',
        'textmessagesgrid.title' : 'Tekstiviestit',
        'textmessagesgrid.sender' : 'Lähettäjä',
        'textmessagesgrid.new' : 'Uusi tekstiviesti',
        'textmessagesgrid.remove' : 'Poista valitut tekstiviestit',
        'textmessagesgrid.emptyPaging' : 'Ei tekstiviestejä',
        'textmessagerecipientsgrid.emptyPaging' : 'Ei vastaanottajia',
        'textmessagerecipientsgrid.title' : 'Viestin vastaanottajat',
        'queued' : 'Lisätty jonoon',
        'sent' : 'Lähetetty',
        'delivered' : 'Toimitettu',
        'textmessages' : 'Tekstiviestit',
        'rowedit.save' : 'Tallenna',
        'rowedit.cancel' : 'Peruuta',
        'phone' : 'Puhelinnumero',
        'dateOfBirth' : 'Syntymäaika',
        'card' : 'Kortti',
        'allowSms' : 'SMS',
        'allowEmail' : '@',
        'clientsgrid.title' : 'Kanta-asiakkaat',
        'clientsgrid.emptyPaging' : 'Ei kanta-asiakkaita',
        'clientsgrid.add' : 'Uusi kanta-asiakas',
        'clientsgrid.remove' : 'Poista valitut',
        'clientsgrid.sendMessage' : 'Lähetä viesti näkyville',
        'preview' : 'Esikatselu',
        'preview.title' : 'Esikatselu (voit sulkea ikkunan klikkaamalla kuvaa)',
        'previewFileId' : 'preview',
        'saveError.title': 'Tietojen tallentaminen epäonnistui',
        'saveError.message': 'Tietojen tallentaminen epäonnistui: ',
        'userpasswordform.title' : 'Käyttäjän salasanan muuttaminen',
        'ok' : 'OK',
        'cancel' : 'Peruuta',
        'passwordMinLength' : 'Salasanan tulee olla vähintään kuusi merkkiä pitkä',
        'validationError.title' : 'Virheellisiä tietoja',
        'validationError.message' : 'Lomakkeella on virheellisiä tietoja.',
        'validationError.password' : 'Salasanat eivät täsmää.',
        'login.title' : 'Kirjautuminen kanta-asiakasrekisteriin',
        'login.waittitle' : 'Kirjautuminen käynnissä',
        'login.waitmessage' : 'Lähetetään tietoja',
        'login.failedtitle' : 'Virhe',
        'login.failedmessage' : 'Kirjautuminen epäonnistui',
        'username' : 'Käyttäjänimi',
        'password' : 'Salasana',
        'login.login' : 'Kirjaudu sisään',
        'maintab.signout' : 'Kirjaudu ulos',
        'clients' : 'Kanta-asiakkaat',
        'instructions' : 'Ohje',
        'users' : 'Käyttäjät',
        'usersgrid.title' : 'Käyttäjät',
        'usersgrid.emptyPaging' : 'Ei käyttäjiä',
        'usersgrid.new' : 'Uusi käyttäjä',
        'usersgrid.remove' : 'Poista valitut käyttäjät',
        'usergroupscombo.emptyText' : 'Käyttäjäryhmä',
        'usergroupsgrid.title' : 'Käyttäjäryhmät',
        'usergroupsgrid.emptyPaging' : 'Ei käyttäjäryhmiä',
        'usergroupsgrid.new' : 'Uusi ryhmä',
        'usergroupsgrid.remove' : 'Poista valitut ryhmät',
        'userform.title' : 'Käyttäjän tietojen muokkaaminen',
        'userform.defaultUserGroupId' : 'Oletusryhmä',
        'userform.setUserPassword' : 'Vaihda salasana',
        'search' : 'Haku',
        'name' : 'Nimi',
        'firstName' : 'Etunimi',
        'lastName' : 'Sukunimi',
        'email' : 'Sähköpostiosoite',
        'timeZone' : 'Aikavyöhyke',
        'passwordAgain' : 'Salasana uudestaan',
        'userName' : 'Käyttäjä',
        'userGroupName' : 'Käyttäjäryhmä',
        'contentType' : 'Tiedostotyyppi',
        'insertionTime' : 'Ladattu',
        'save' : 'Tallenna muutokset',
        'saveandclose' : 'Tallenna muutokset ja sulje',
        'close' : 'Sulje',
        'closewithoutsaving' : 'Sulje tallentamatta muutoksia',
        'usergroupitemsgrid.title' : 'Oikeudet käyttäjäryhmissä',
        'usergroupitemsgrid.emptyPaging' : 'Ei oikeuksia käyttäjäryhmissä',
        'usergroupitemsgrid.remove' : 'Poista valitut käyttäjäoikeudet',
        'users.addReadPerm' : 'Lisää lukuoikeus valituille käyttäjille valittuihin ryhmiin',
        'users.addWritePerm' : 'Lisää luku- ja kirjoitusoikeus valituille käyttäjille valittuihin ryhmiin',
        'smsgrid.fileName' : 'Tiedosto',
        'amount' : 'Summa',
        'insertionTime' : 'Lisätty',
        'upload.title' : 'Tiedostojen lataus',
        'upload.button' : 'Lisää tositteita tiputtamalla tiedostoja tähän.',
        'upload.uploading' : 'Ladataan...',
        'usergroupform.title' : 'Käyttäjäryhmän tietojen muokkaaminen',
        'usergroupform.mailChimpApiKey' : 'MailChimp API-key',
        'usergroupform.mailChimpListName' : 'MailChimp listan nimi',
        'emptyMonthCombo' : 'Suodata lista syntymäkuukauden perusteella',
        'month1' : 'Tammikuu',
        'month2' : 'Helmikuu',
        'month3' : 'Maaliskuu',
        'month4' : 'Huhtikuu',
        'month5' : 'Toukokuu',
        'month6' : 'Kesäkuu',
        'month7' : 'Heinäkuu',
        'month8' : 'Elokuu',
        'month9' : 'Syyskuu',
        'month10': 'Lokakuu',
        'month11': 'Marraskuu',
        'month12' : 'Joulukuu',
        'clientsgrid.export' : 'Lataa kaikki XLSX-muodossa'
    };
    /*
     strings = {
        'textmessageform.title' : 'Modifying text message to send',
        'text' : 'Text',
        'textEditor' : 'Text',
        'textmessageform.abort' : 'Abort sending text message',
        'textmessageform.send' : 'Send text message to recipients',
        'textmessageform.replyToText' : 'Reply to message',
        'receivedtextmessageform.title' : 'Received text message',
        'receivedtextmessageform.reply' : 'Reply to text message',
        'textmessageform.length' : 'Text message length',
        'textmessageform.lengthMessage' : '{0} characters, {1} messages, {2} characters per message. Remaining characters: {3}',
        'textmessagesgrid.title' : 'Text messages',
        'textmessagesgrid.sender' : 'Sender',
        'textmessagesgrid.new' : 'New text message',
        'textmessagesgrid.remove' : 'Remove selected text messages',
        'textmessagesgrid.emptyPaging' : 'No text messages',
        'textmessagerecipientsgrid.emptyPaging' : 'No recipients',
        'textmessagerecipientsgrid.title' : 'Message recipients',
        'queued' : 'Queued',
        'sent' : 'Sent',
        'delivered' : 'Delivered',
        'textmessages' : 'Text messages',
        'rowedit.save' : 'Save',
        'rowedit.cancel' : 'Cancel',
        'phone' : 'Phone number',
        'dateOfBirth' : 'Date of birth',
        'card' : 'Card',
        'allowSms' : 'SMS',
        'allowEmail' : '@',
        'clientsgrid.title' : 'Clients',
        'clientsgrid.emptyPaging' : 'No clients',
        'clientsgrid.add' : 'Uusi kanta-asiakas',
        'clientsgrid.remove' : 'Remove selected clients',
        'clientsgrid.sendMessage' : 'Send message to the clients in the list',
        'saveError.title': 'Request failed.',
        'saveError.message': 'Request failed: ',
        'userpasswordform.title' : 'Setting user password',
        'ok' : 'OK',
        'cancel' : 'Cancel',
        'passwordMinLength' : 'Password must contain at least six characters.',
        'validationError.title' : 'Validation error',
        'validationError.message' : 'The form validation failed.',
        'validationError.password' : 'The passwords are mismatching.',
        'login.title' : 'Login',
        'login.waittitle' : 'Login in progress',
        'login.waitmessage' : 'Sending information',
        'login.failedtitle' : 'Error',
        'login.failedmessage' : 'Login failed',
        'username' : 'Username',
        'password' : 'Password',
        'login.login' : 'Login',
        'maintab.signout' : 'Logout',
        'clients' : 'Clients',
        'users' : 'Users',
        'usersgrid.title' : 'Users',
        'usersgrid.emptyPaging' : 'No users',
        'usersgrid.new' : 'New user',
        'usersgrid.remove' : 'Remove selected users',
        'usergroupscombo.emptyText' : 'User group',
        'usergroupsgrid.title' : 'User groups',
        'usergroupsgrid.emptyPaging' : 'No user groups',
        'usergroupsgrid.new' : 'New user group',
        'usergroupsgrid.remove' : 'Remove selected user groups',
        'userform.title' : 'Modifying user information',
        'userform.defaultUserGroupId' : 'Default user group',
        'userform.setUserPassword' : 'Change password',
        'search' : 'Search',
        'name' : 'Name',
        'firstName' : 'First name',
        'lastName' : 'Last name',
        'email' : 'Email',
        'timeZone' : 'Time zone',
        'passwordAgain' : 'Password again',
        'userName' : 'User',
        'userGroupName' : 'User group',
        'insertionTime' : 'Insertion time',
        'save' : 'Save changes',
        'saveandclose' : 'Save changes and close',
        'close' : 'Close',
        'closewithoutsaving' : 'Close without saving changes',
        'usergroupitemsgrid.title' : 'User group permissions',
        'usergroupitemsgrid.emptyPaging' : 'No user group permissions',
        'usergroupitemsgrid.remove' : 'Remove selected user group permissions.',
        'users.addReadPerm' : 'Add read permission for the selected users to selected groups',
        'users.addWritePerm' : 'Add read and write permission for the selected users to selected groups',
        'usergroupform.title' : 'Modifying user group',
        'usergroupform.mailChimpApiKey' : 'MailChimp API-key',
        'usergroupform.mailChimpListName' : 'MailChimp list name',
        'emptyMonthCombo' : 'Filter list by month of birth',
        'month1' : 'January',
        'month2' : 'February',
        'month3' : 'Match',
        'month4' : 'April',
        'month5' : 'May',
        'month6' : 'June',
        'month7' : 'July',
        'month8' : 'August',
        'month9' : 'September',
        'month10': 'October',
        'month11': 'November',
        'month12' : 'December'
    };
        */
    var parts = k.split('.');
    if (k in strings) {
        while (k in strings) {
            var pk = k;
            k = strings[k];
            if (pk == k)
                break;
        }
        return k;
    } else if (parts[parts.length - 1] in strings) {
        k = parts[parts.length - 1];
        while (k in strings) {
            var pk = k;
            k = strings[k];
            if (pk == k)
                break;
        }
        return k;
    } else if (d) {
        return __(d);
    } else {
        return k;
    }
};
